
# ============================================================
# DATA CLEANING & TRANSFORMATION SCRIPT
# Tutorial 3: AI-Assisted Data Quality Management
# Dataset: customer_shopping_behavior.csv
# Generated by: Claude (Anthropic) based on Airia pipeline analysis
# Date: June 2026
# ============================================================

import pandas as pd
import numpy as np
import re

# ============================================================
# STEP 0: LOAD DATASET
# Load raw CSV file into pandas DataFrame for processing
# ============================================================

df = pd.read_csv('customer_shopping_behavior.csv')

print('=' * 60)
print('DATA CLEANING SCRIPT - Customer Shopping Behavior')
print('=' * 60)
print('')
print('BEFORE CLEANING:')
print('Total rows:', len(df))
print('Total columns:', len(df.columns))
print('')
print('Missing values per column:')
print(df.isnull().sum())
print('')

original_count = len(df)

# ============================================================
# STEP 1: STANDARDIZE COLUMN NAMES
# Remove leading/trailing whitespace from column names
# ============================================================

df.columns = df.columns.str.strip()
print('STEP 1: Column names standardized')

# ============================================================
# STEP 2: STANDARDIZE CUSTOMER ID FORMAT
# Expected format: CUST##### (e.g. CUST10111)
# Issues: missing prefix, lowercase, hyphen separator
# Fix: extract digits and prepend CUST
# ============================================================

id_col = [c for c in df.columns if 'customer' in c.lower() and 'id' in c.lower()][0]

def standardize_customer_id(cid):
    if pd.isna(cid):
        return cid
    cid = str(cid).strip()
    digits = re.sub(r'[^0-9]', '', cid)
    if digits:
        return 'CUST' + digits
    return cid

df[id_col] = df[id_col].apply(standardize_customer_id)
print('STEP 2: Customer ID standardized to CUST##### format')

# ============================================================
# STEP 3: CLEAN AGE FIELD
# Issues: text mixed with numeric ("47 yrs"), negative values,
#         unrealistic values (2.0, 110.0)
# Fix: extract numeric, invalidate out-of-range, impute median
# ============================================================

age_col = [c for c in df.columns if 'age' in c.lower()][0]

def clean_age(val):
    if pd.isna(val):
        return np.nan
    val = str(val).strip()
    match = re.search(r'(\d+\.?\d*)', val)
    if match:
        return float(match.group(1))
    return np.nan

df[age_col] = df[age_col].apply(clean_age)

invalid_age_count = ((df[age_col] < 16) | (df[age_col] > 100)).sum()
df[age_col] = df[age_col].where((df[age_col] >= 16) & (df[age_col] <= 100), other=np.nan)

age_median = df[age_col].median()
df[age_col] = df[age_col].fillna(age_median)
print('STEP 3: Age cleaned -', invalid_age_count, 'invalid values removed, missing imputed with median:', age_median)

# ============================================================
# STEP 4: CLEAN PURCHASE AMOUNT
# Issues: negative values, extreme outliers (3120.82, 3825.71)
# Fix: remove negatives, flag outliers, impute missing with median
# ============================================================

amt_col = [c for c in df.columns if 'purchase' in c.lower() and 'amount' in c.lower()][0]

df[amt_col] = pd.to_numeric(df[amt_col], errors='coerce')

negative_amt_count = (df[amt_col] < 0).sum()
df[amt_col] = df[amt_col].where(df[amt_col] >= 0, other=np.nan)

Q1 = df[amt_col].quantile(0.25)
Q3 = df[amt_col].quantile(0.75)
IQR = Q3 - Q1
upper_fence = Q3 + (1.5 * IQR)
df['Purchase_Amount_Outlier_Flag'] = df[amt_col] > upper_fence
outlier_count = df['Purchase_Amount_Outlier_Flag'].sum()

amt_median = df[amt_col].median()
df[amt_col] = df[amt_col].fillna(amt_median)
print('STEP 4: Purchase Amount cleaned -', negative_amt_count, 'negatives removed,', outlier_count, 'outliers flagged, missing imputed with median:', round(amt_median, 2))

# ============================================================
# STEP 5: CLEAN PREVIOUS PURCHASES
# Issues: negative count (CUST10084: -3) - impossible value
# Fix: set negative to NaN, impute with median
# ============================================================

prev_cols = [c for c in df.columns if 'previous' in c.lower()]
if prev_cols:
    prev_col = prev_cols[0]
    df[prev_col] = pd.to_numeric(df[prev_col], errors='coerce')
    negative_prev_count = (df[prev_col] < 0).sum()
    df[prev_col] = df[prev_col].where(df[prev_col] >= 0, other=np.nan)
    prev_median = df[prev_col].median()
    df[prev_col] = df[prev_col].fillna(prev_median)
    print('STEP 5: Previous Purchases cleaned -', negative_prev_count, 'negatives removed')

# ============================================================
# STEP 6: REMOVE DUPLICATE RECORDS
# Issues: 31 duplicate records (3.1% of dataset)
# Fix: remove exact duplicates then duplicate Customer IDs
# ============================================================

before_dedup = len(df)
df = df.drop_duplicates()
df = df.drop_duplicates(subset=[id_col], keep='first')
duplicates_removed = before_dedup - len(df)
print('STEP 6: Duplicates removed:', duplicates_removed, 'records')

# ============================================================
# STEP 7: FIX TRUNCATED FREQUENCY OF PURCHASE
# Issue: CUST10549 has "Bi-Wee" instead of "Bi-Weekly"
# Fix: direct string replacement
# ============================================================

freq_cols = [c for c in df.columns if 'frequency' in c.lower()]
if freq_cols:
    freq_col = freq_cols[0]
    df[freq_col] = df[freq_col].str.strip()
    df[freq_col] = df[freq_col].replace({'Bi-Wee': 'Bi-Weekly'})
    print('STEP 7: Truncated Bi-Wee corrected to Bi-Weekly')

# ============================================================
# STEP 8: STANDARDIZE GENDER FIELD
# Issues: 8 variations (F, M, Female, Male, female, male, FEMALE, MALE)
# Fix: map all to Male/Female, impute missing with mode
# ============================================================

gender_col = [c for c in df.columns if 'gender' in c.lower()][0]

def standardize_gender(val):
    if pd.isna(val):
        return np.nan
    val = str(val).strip().upper()
    if val in ['F', 'FEMALE']:
        return 'Female'
    elif val in ['M', 'MALE']:
        return 'Male'
    return np.nan

df[gender_col] = df[gender_col].apply(standardize_gender)
gender_mode = df[gender_col].mode()[0]
missing_gender = df[gender_col].isna().sum()
df[gender_col] = df[gender_col].fillna(gender_mode)
print('STEP 8: Gender standardized to Male/Female -', missing_gender, 'missing imputed with mode:', gender_mode)

# ============================================================
# STEP 9: STANDARDIZE PAYMENT METHOD FIELD
# Issues: 17 variations including CC, double spaces, mixed case
# Fix: map all to 5 standard categories, impute missing with mode
# ============================================================

pay_col = [c for c in df.columns if 'payment' in c.lower()][0]

def standardize_payment(val):
    if pd.isna(val):
        return np.nan
    val = str(val).strip().upper()
    val = ' '.join(val.split())
    if val == 'CASH':
        return 'Cash'
    elif val in ['CC', 'CREDIT CARD', 'CREDITCARD']:
        return 'Credit Card'
    elif val in ['DEBIT CARD', 'DEBITCARD']:
        return 'Debit Card'
    elif val in ['PAYPAL', 'PAY PAL']:
        return 'PayPal'
    elif val in ['BANK TRANSFER', 'BANKTRANSFER']:
        return 'Bank Transfer'
    return np.nan

df[pay_col] = df[pay_col].apply(standardize_payment)
pay_mode = df[pay_col].mode()[0]
missing_pay = df[pay_col].isna().sum()
df[pay_col] = df[pay_col].fillna(pay_mode)
print('STEP 9: Payment Method standardized to 5 categories -', missing_pay, 'missing imputed with mode:', pay_mode)

# ============================================================
# STEP 10: STANDARDIZE SUBSCRIPTION STATUS
# Issues: 7 variations (Y, YES, Yes, yes, N, NO, No, n)
# Fix: map all to Yes/No, impute missing with mode
# ============================================================

sub_cols = [c for c in df.columns if 'subscription' in c.lower()]
if sub_cols:
    sub_col = sub_cols[0]

    def standardize_subscription(val):
        if pd.isna(val):
            return np.nan
        val = str(val).strip().upper()
        if val in ['Y', 'YES']:
            return 'Yes'
        elif val in ['N', 'NO']:
            return 'No'
        return np.nan

    df[sub_col] = df[sub_col].apply(standardize_subscription)
    sub_mode = df[sub_col].mode()[0]
    missing_sub = df[sub_col].isna().sum()
    df[sub_col] = df[sub_col].fillna(sub_mode)
    print('STEP 10: Subscription Status standardized to Yes/No -', missing_sub, 'missing imputed with mode:', sub_mode)

# ============================================================
# STEP 11: CLEAN REVIEW RATING
# Issues: values above 5.0 (7.5 found in 2 records)
# Fix: cap at 5.0, impute missing with median
# ============================================================

rating_cols = [c for c in df.columns if 'rating' in c.lower() or 'review' in c.lower()]
if rating_cols:
    rating_col = rating_cols[0]
    df[rating_col] = pd.to_numeric(df[rating_col], errors='coerce')
    above_5_count = (df[rating_col] > 5.0).sum()
    df[rating_col] = df[rating_col].clip(upper=5.0)
    rating_median = df[rating_col].median()
    missing_rating = df[rating_col].isna().sum()
    df[rating_col] = df[rating_col].fillna(rating_median)
    print('STEP 11: Review Rating cleaned -', above_5_count, 'values capped at 5.0,', missing_rating, 'missing imputed with median:', rating_median)

# ============================================================
# STEP 12: FIX LOCATION FIELD
# Issues: Unknown entries and 23 missing values
# Fix: replace Unknown with NaN, impute with mode
# ============================================================

loc_cols = [c for c in df.columns if 'location' in c.lower()]
if loc_cols:
    loc_col = loc_cols[0]
    df[loc_col] = df[loc_col].str.strip()
    df[loc_col] = df[loc_col].replace({
        'Unknown': np.nan,
        'unknown': np.nan,
        'UNKNOWN': np.nan
    })
    loc_mode = df[loc_col].mode()[0]
    missing_loc = df[loc_col].isna().sum()
    df[loc_col] = df[loc_col].fillna(loc_mode)
    print('STEP 12: Location cleaned -', missing_loc, 'missing values imputed with mode:', loc_mode)

# ============================================================
# STEP 13: FILL ALL REMAINING MISSING VALUES
# Strategy: median for numeric, mode for categorical
# ============================================================

print('')
print('STEP 13: Filling any remaining missing values...')

for col in df.select_dtypes(include='number').columns:
    missing = df[col].isna().sum()
    if missing > 0:
        median_val = df[col].median()
        df[col] = df[col].fillna(median_val)
        print('  Filled', col, '-', missing, 'values with median:', round(median_val, 2))

for col in df.select_dtypes(include=['object']).columns:
    missing = df[col].isna().sum()
    if missing > 0:
        mode_val = df[col].mode()[0]
        df[col] = df[col].fillna(mode_val)
        print('  Filled', col, '-', missing, 'values with mode:', mode_val)

# ============================================================
# STEP 14: FINAL VALIDATION AND SUMMARY REPORT
# ============================================================

print('')
print('=' * 60)
print('CLEANING COMPLETE - SUMMARY REPORT')
print('=' * 60)
print('')
print('Record counts:')
print('  Original records:', original_count)
print('  Cleaned records:', len(df))
print('  Records removed:', original_count - len(df))
print('  Data retention rate:', round((len(df) / original_count) * 100, 1), '%')
print('')
print('Missing values after cleaning:')
missing_after = df.isnull().sum()
if missing_after.sum() == 0:
    print('  No missing values remaining')
else:
    print(missing_after[missing_after > 0])
print('')
print('Value counts - Gender:')
print(df[gender_col].value_counts())
print('')
print('Value counts - Payment Method:')
print(df[pay_col].value_counts())
print('')
print('Value counts - Subscription Status:')
if sub_cols:
    print(df[sub_col].value_counts())
print('')
print('Age statistics:')
print('  Min:', df[age_col].min())
print('  Max:', df[age_col].max())
print('  Mean:', round(df[age_col].mean(), 1))
print('')
print('Purchase Amount statistics:')
print('  Min:', round(df[amt_col].min(), 2))
print('  Max:', round(df[amt_col].max(), 2))
print('  Mean:', round(df[amt_col].mean(), 2))
print('  Outliers flagged:', df['Purchase_Amount_Outlier_Flag'].sum())
print('')

# ============================================================
# STEP 15: SAVE CLEANED DATASET
# ============================================================

df.to_csv('cleaned_customer_shopping_behavior.csv', index=False)
print('Cleaned dataset saved as: cleaned_customer_shopping_behavior.csv')
print('Final shape:', df.shape[0], 'rows x', df.shape[1], 'columns')
print('')
print('Ready for analysis!')
